// <auto-generated>
// This file is from a seed project.
// </auto-generated>

using Abp.Application.Services.Dto;
using Abp.AutoMapper;
using System;

namespace EasyLife.Personal.EncryptedImportantThings.Dto
{
    /// <summary>
    /// CreateOrEditEncryptedImportantInformationDto
    /// </summary>
    [AutoMapFrom(typeof(Personal.EncryptedImportantThings.EncryptedImportantInformation))]
    public class CreateOrEditEncryptedImportantInformationDto : EntityDto<Guid>
    {
        /// <summary>
        /// Title
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// EncryptedText
        /// </summary>
        public string EncryptedText { get; set; }
        /// <summary>
        /// UserId
        /// </summary>
        public long UserId { get; set; }
    }
}
